[package]
name = "moteus_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
cu29 = { workspace = true }
serde = { workspace = true }
common = { workspace = true }
moteus = { workspace = true }
bincode = { version = "2.0", package = "cu-bincode", default-features = false, features = ["derive", "alloc"] }
