[workspace]
members = [
    "apps/cu_example_app",
    "apps/masterpiece",
    "apps/proto",
    "components/bridges/moteus_bridge", "components/tasks/diffdrive",
    "components/payloads/common", "components/sources/oakd_lite_source", "components/tasks/field_oriented_diff_drive", "components/tasks/iekflocalizer",     "components/tasks/accel_limiter",
    "components/tasks/moteus_tasks", "components/tasks/sotm_rt", "external/evosim", "components/sources/Joy", "components/tasks/Prototyping", "components/payloads/driver_station", "components/tasks/turret_tasks", "components/sinks/evoviz", "components/sinks/rpsinks", "evods", "components/sources/BNOSource"]
resolver = "2"

[profile.dev]
opt-level = 1

[workspace.dependencies]
cu29 = "1.1.0"
cu-spatial-payloads = "1.1.0"
cu-sensor-payloads = "1.1.0"
cu-apriltag = "1.1.0"
cu-logmon = "1.0.1"
cu29-export = { version = "*"  }
serde = { version = "*", features = ["derive"] }
nalgebra = "0.34.2"
rerun = "0.33.1"
ordered-float = "5.3.0"
pid = "4.0.0"
kalman_filters = { version = "1.0.1", features = ["nalgebra"] }
kfilter = "0.5.1"
sophus = "0.15.0"
moteus = "0.5.3"
rapier2d = "0.33.0"
glam = "0.33.2"
bincode = { version = "2.0", package = "cu-bincode", default-features = false, features = ["derive", "alloc"] }
crossbeam-channel = "0.5"
tokio = { version = "1", features = ["rt", "macros", "time", "sync"] }
zenoh = { version = "1.9.0", default-features = false, features = ["transport_tcp", "transport_udp", "transport_unixsock-stream"] }
gilrs = "0.11"
serde_json = "1"
dioxus = { version = "=0.7.9", features = ["desktop"] }
#internal deps
common = { path = "./components/payloads/common/" }
driver_station = { path = "./components/payloads/driver_station/" }

moteus_bridge = { path = "./components/bridges/moteus_bridge/" }
oakd_lite_source = { path = "./components/sources/oakd_lite_source/" }
accel_limiter = { path = "./components/tasks/accel_limiter/" }
diffdrive = { path = "./components/tasks/diffdrive/" }
field_oriented_diff_drive = { path = "./components/tasks/field_oriented_diff_drive/" }
iekflocalizer = { path = "./components/tasks/iekflocalizer/" }
moteus_tasks = { path = "./components/tasks/moteus_tasks/" }
evosim = { path = "./external/evosim/" }
Joy = { path = "./components/sources/Joy/" }
Prototyping = { path = "./components/tasks/Prototyping/" }
