[package]
name = "masterpiece"
version = "0.1.0"
edition = "2021"
default-run = "masterpiece"

# The main executable of your application
[[bin]]
name = "masterpiece"
path = "src/main.rs"

[[bin]]
name = "masterpiece-sim"
path = "src/sim.rs"

[[bin]]
name = "masterpiece-logreader"
path = "src/logreader.rs"
required-features = ["logreader"]

[[bin]]
name = "masterpiece-resim"
path = "src/resim.rs"
required-features = ["sim-debug"]

[features]
default = []
logreader = ["dep:cu29-export"]
sim-debug = ["logreader", "cu29/reflect", "cu29/remote-debug"]

[dependencies]
cu29 = { workspace = true }
cu29-export = { workspace = true, optional = true }
serde = { workspace = true }
rapier2d = { workspace = true }
glam = { workspace = true }
common = { workspace = true }

moteus_bridge = { workspace = true }
oakd_lite_source = { workspace = true }
accel_limiter = { workspace = true }
diffdrive = { workspace = true }
diffdrive_odometry = { workspace = true }
field_oriented_diff_drive = { workspace = true }
iekflocalizer = { workspace = true }
moteus_tasks = { workspace = true }
